scripts/dockerfiles/Dockerfile-base

Better to put it in the Dockerfile, but fissile currently
doesn't let us do that.  So I've added https://jira.hpcloud.net/browse/HCF-758
to request this.

HCF-678 - Acceptance tests need scp and sftp

---

compilator/compilator.go
compilator/compilator_test.go
docker/docker.go
docker/docker_test.go

Let's try a volume at `/var/vcap/sources` ­— that _should_ be where configure is running. Probably.
Not for merge yet (this is to cause CI to happen)

HCF-926 tar fails to compile

---

app/fissile.go
builder/role_image.go
builder/role_image_test.go
cmd/build-images.go
docker/docker.go
docker/docker_test.go
model/job.go

Turns out we already have a thing that builds images in parallel, it just does non-release images and we never use it.

HCF-949 build role images in parallel

---

builder/role_image.go
builder/role_image_test.go
scripts/dockerfiles/run.sh

Creating PR for configgin changes. ~~This isn't ready to merge until https://github.com/hpcloud/configgin/pull/49 is merged to master, at which point the submodule here can be updated.~~

HCF-1132 Generate job_config.json for batch run.sh

---

make/package

In combo with this PR: https://github.com/hpcloud/fissile-ci/pull/16

HCF-1144 Revert "Fix make/package"

---

app/fissile.go
kube/pod.go
kube/pod_test.go
kube/service.go
kube/utils.go
kube/utils_test.go

The port names were wrong, so the services weren't working correctly.  Also some compat fixes.

Fixes for kubed CF

---

README.md

Documentation describe how to build or install fissile

Update documentation how to build and install fissile

---

README.md
docs/fissile-environment.md

This PR extends documentation for fissile environment setup.

Documentation how to setup fissile environment

---

README.md

This PR adds two missing steps in the README.md which are needed to build fissile.

Missing Readme steps

---

LICENSE.md

Copyright was transferred from HPE to SUSE

Fix copyright statement

---

.gitignore
app/validation.go
builder/packages_image.go
builder/packages_image_test.go
builder/role_image.go
docker/docker.go
docker/docker_test.go
model/job.go
model/job_test.go
model/opinions.go
model/opinions_test.go
model/roles.go
scripts/dockerfiles/Dockerfile-packages

Trello: https://trello.com/c/IemiPFAX/105-fissile-doesn-t-detect-opinion-changes-so-it-doesn-t-rebuild-images
Stacked on https://github.com/SUSE/fissile/pull/239
because of the similarity (same area of code),  tested together.

Trigger rebuild for opinion changes

---

kube/pod.go
kube/pod_test.go
model/roles.go

Partially still a WIP: Have to update and extend the unit tests.
Should be reviewable tough, and should be working.

Extended liveness and other probes

---

app/fissile.go
app/fissile_test.go
cmd/root.go
cmd/show-properties.go
cmd/show-release.go
kube/job_test.go
kube/service_test.go
kube/stateful_set_test.go
make/build
model/job.go
model/job_template.go
model/job_template_test.go
model/job_test.go
model/models.go
model/models_test.go
model/package.go
model/package_test.go
model/release.go
model/release_test.go
testhelpers/serialization_helper.go
util/serialization_helper.go
util/serialization_helper_test.go

Implement `fissile show releases --output=<json|yaml>`

---

cmd/root.go

This makes it easier for CI to use resources better.

Automatically determine the number of workers to use

---

scripts/dockerfiles/run.sh

This sets up the instance id to actually be a number.  Assumes the host name is either the instance id directory (`foo-1`) or a random string sequence (`foo-xyz12`).

run.sh: set up /var/vcap/instance/id

---

kube/deployment.go
kube/job.go
kube/stateful_set.go
kube/utils.go

Add role description to Job objects.
Sort replica min/max to the top of Deployment spec files.

Helm chart improvements

---

app/fissile.go
cmd/build-helm.go
cmd/build-kube.go
cmd/root.go
kube/deployment.go
kube/export_settings.go
kube/job.go
kube/job_test.go
kube/pod.go
kube/pod_test.go
kube/registry_credentials.go
kube/secret.go
kube/service.go
kube/service_test.go
kube/stateful_set.go
kube/stateful_set_test.go
kube/values.go
util/name_sanitization.go
util/name_sanitization_test.go

This is a rebased version of #284 which had merge conflicts with `master`.

Use template for docker images

---

kube/service.go
kube/values.go

https://trello.com/c/NEiNplMX/453-2-expose-services-using-configured-load-balancer-via-helm
Limited testing under vagrant:
💚 for `loadbalanced: false`, and :boom: for `loadbalanced: true` (unable to create the requested LBs).
Rebased and cleaned up history.

Control the use of loadbalancers for services.

---

app/fissile.go
kube/secret.go
scripts/dockerfiles/run.sh

Small fissile tweaks to get rid of all the dev cert generation in SCF.

Cleanup cert gen

---

app/fissile.go
app/fissile_test.go
test-assets/role-manifests/exposed-ports-no-ports.yml
testhelpers/serialization_helper.go

Fissile: check that roles with no ports can be written

---

app/fissile.go
kube/export_settings.go
kube/pod.go
kube/pod_test.go
kube/secret.go
util/name_to_key.go
util/name_to_key_test.go

Ref: https://trello.com/c/sWAKVtIS/551-3-use-versioned-secrets-to-avoid-race-condition
For all related PRs (fissile, scf-secret-generator, uaa-fissile-release, scf)

sWAKVtIS Emit references to versioned main secrets.

---

scripts/dockerfiles/run.sh

Avoid type mismatches with `configgin`.
https://trello.com/c/8RKI6NUG/604-transmogrify-undefined-method-zero

Change the processing of component indices

---

docs/configuration.md
docs/validator-description.md
kube/deployment_test.go
kube/job_test.go
kube/pod.go
kube/pod_test.go
model/mustache.go
model/mustache_test.go
scripts/dockerfiles/run.sh
testhelpers/helm_helper.go

It will be used by the secrets-generator to determine if previous secrets should exist or not.

Add HELM_IS_INSTALL built-in variable

---

kube/pod.go

Ref: https://trello.com/c/b5kQaco7/729-3-implement-brain-tests-for-persi-nfs
Fissile work for the NFS persi brain test.

Added support for additional special variable to provide storage class information

---

model/release.go
model/release_test.go
test-assets/ntp-final-release/release.MF
test-assets/ntp-release/dev_releases/ntp/ntp-2+dev.3.yml

This PR is to fix issue : https://github.com/SUSE/fissile/issues/383

bug fix: fissile build error when commit_hash is a scientific format string

---

kube/deployment.go
kube/deployment_test.go
kube/job.go
kube/job_test.go
kube/kube_test.go
kube/pod.go
kube/pod_test.go
kube/registry_credentials.go
kube/registry_credentials_test.go
kube/secret.go
kube/secret_test.go
kube/stateful_set.go
kube/utils.go
kube/utils_test.go

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md#standard-labels
[trello#ztQqeRs9]

Add recommended labels to kube objects

---

README.md

Update for https://www.pivotaltracker.com/story/show/160012768

Add docs for the using NATS release

---

docs/configuration.md
model/instance_groups.go
model/role_run.go
model/roles_test.go
model/validation.go

It has been replaced by bosh_containerization.ports

Remove vestigial bosh_containerization.run.exposed-ports field

---

kube/pod.go
kube/pod_test.go

Cherry-pick of #444 into develop

 kube/pod.go: force allowPrivilegeEscalation if privileged
