- builder/role_image.go
- builder/role_image_test.go
- model/roles.go
- model/roles_test.go
- scripts/dockerfiles/run.sh
- test-assets/role-manifests/tor-good.yml
We can now have absolute paths in `scripts:` and `post_config_scripts:` in the role manifest.  They will *not* be copied into the image (instead they're assumed to already exist), and will be run via `bash`.
Also cleaned up `run.sh` to make it more readable.
> HCF 750 allow custom script paths

- model/roles.go
The ordering of jobs within a role may be significant (for bosh-task roles where each job is run sequentially).  Package order, however, is not significant and should still be sorted.
> HCF-732 Don't sort role jobs when calculating versions

- scripts/dockerfiles/Dockerfile-base
There is already a monit logrotate config created during its installation.
It looks like this:
```
/var/log/monit.log {
rotate 4
weekly
minsize 1M
missingok
create 640 root adm
notifempty
compress
delaycompress
postrotate
invoke-rc.d monit reload > /dev/null
endscript
}
```
All that's needed is fixing the log path from the default to the one we set in `monitrc.erb`
> HCF-908 Fix path in monit logrotate config

- scripts/dockerfiles/Dockerfile-base
- scripts/dockerfiles/run.sh
Monit is actually a terrible init (which it really wasn't designed to be — it only does monitoring, not signal handling).  That caused things to be horribly broken.  Use dumb-init (which only does the signal handling)
instead.  Since SIGINT/SIGTERM are still forwarded to monit, that doesn't break anything.
> HCF-958 Use dumb-init as init rather than monit

- builder/role_image.go
- compilator/compilator.go
- compilator/compilator_test.go
- model/package.go
Locally tested for empty, partially complete, and complete cache.
- Placed code gathering the packages in a new function (`gatherPackages`). => Shared with tests.
- Reworked gathering to take only one package per equivalence set. (keyed on fingerprints). Removed `initPackageMaps`, now integrated with new `gatherPackages`.
- Renamed `packageDone` to `signalDependencies` to reduce confusion. Now based on fingerprints.
- Changed structure of disk cache to use only fingerprints, not package names. We have packages with identical fingerprints and different names (Example: hcf-sso/golang1.6 vs garden-linux/golang_1.6.1).
__Attention__: hcf's `make/compile` has to be adapted to the new structure.
- Moved the compilator functions computing paths into the cache to model/package. => Shared between …
> [HCF-1011] Properly move to the use of (source) fingerprints for package identification and referencing in all things.

- app/fissile.go
- app/fissile_test.go
- builder/packages_image.go
- builder/packages_image_test.go
- builder/role_image_test.go
- compilator/compilator.go
- compilator/compilator_test.go
- docker/docker.go
- docker/docker_test.go
- scripts/dockerfiles/Dockerfile-packages
Instead of copying all the compiled files to a scratch workspace and telling docker to build from there, just build the tar file ourselves (which is what would have happened before too).  This reduces a set of read/write that didn't need to happen.
In tests, it reduced rebuilding the packages layer image from ~4:30 to ~3:40.
> HCF-583 Reduce copying when building packages layer image

- scripts/dockerfiles/monitrc.erb
It's already being logged to stdout (which gets handled by our docker logging infrastructure), there's no need to keep a copy on disk in a container.
> HCF-1056 disable monit logging to disk

- builder/packages_image_test.go
- scripts/dockerfiles/Dockerfile-packages
We, umm, somehow forgot to actually put that in there.
> HCF-583 Actually embed the fingerprints as labels

- builder/packages_image_test.go
We don't care about the _order_ of the fingerprints when used as docker image labels, so sort them before comparison.
> builder: package images test: fix flaky test

- config-store/config_store.go
- config-store/config_store_test.go
- config-store/config_writer_json_provider.go
- config-store/config_writer_json_provider_test.go
- test-assets/ntp-release/jobs/ntpd/spec
- util/json_helper.go
- util/json_helper_test.go
That is, default properties from one release should not have any effect on jobs from a different release, even when they are in the same role.
> HCF-1057 Make sure that default properties are isolated to each release

- cmd/build-layer.go
- cmd/root.go
Let the `build layer` use only the basic validation, excluding the bogus/superfluous release validation.
> [HCF-1074] Refactor the root PersistentPreRunE

- app/fissile.go
- app/fissile_test.go
- cmd/build-cleancache.go
- cmd/build-images.go
- cmd/build-packages.go
- cmd/show-image.go
- cmd/show-properties.go
- cmd/show-release.go
Removes package data not referenced (anymore) by the loaded release(s) from the local compilation cache.
> [HCF-1080] New sub command "build cleancache". 

- .gitmodules
- Makefile
- app/fissile.go
- builder/base_image.go
- builder/base_image_test.go
- cmd/build-layer-stemcell.go
- cmd/root.go
- make/bindata
- make/configgin
This embeds configgin into the fissile binary so we never end up using the wrong version.  It does so by submoduling configgin (using the public URL) and go-bindata.
This _does_ bloat the size of the binary from 15M to 23M for me, though.
> HCF-1112 embed configgin

- make/clean
- make/configgin
Also add configgin build results to `make clean` target and calls
`make dist` instead of invoking `make/package` to build configgin.
> HCF-1122 Update configgin to build on OS X

- make/build
- make/package
CI part of this PR: https://github.com/hpcloud/fissile-ci/pull/13
Some notes:
* `build` no longer builds the fissile binary straight into the working repo, but into a `build/<os-and-arch>` folder, as with the cf plugins Makefiles. It sets the golang `$GOOS` env var before building.
* `dist` still creates a `.tgz` with the same name format, just creates a second .tgz now.
* `clean` didn't need to be changed, as it already deleted any folder named `build` (Leftovers from a previous folder structure?)
* I didn't test the new darwin fissile binary on OSX.
> HCF-1144 Enable OSX build and dist

- Makefile
- make/package
A previous commit had removed the `build` step from `package`.
> Fix make/package

- make/format
- make/include/colors.sh
- make/lint
When the program (golint / goimports) reports an error — for example because they were not installed - we should correctly fail.
This fixes the issue by getting rid of the pipe so `errexit` is still in effect.  While we're there, get rid of the `wc` too, since we can just test for an empty file.  That means always removing the file during the trap, rather than early, which lets us unconditionally cat it too.
Also fixes problems identified by shellcheck.
> HCF-1167 make lint/format should fail on error

- builder/base_image.go
- scripts/dockerfiles/Dockerfile-base
- scripts/dockerfiles/monitrc.erb
- scripts/dockerfiles/post-start.sh
- scripts/dockerfiles/run.sh
Collapsed the history, dropped the transient monit, as per the last comment from yesterday.
The new form with a dynamically created job checking the dependencies and starting the post-start stuff when things are up worked out very well and looks to be much simpler.
Local tests ... All working.
> [HCF-1155][HCF-776] Implement support for post-start scripts.

- scripts/dockerfiles/rsyslog_conf/etc/logrotate.d/hcf
- scripts/dockerfiles/rsyslog_conf/etc/logrotate.d/rsyslog
Use "copytruncate" for all logs other than the ones in /var/vcap (they're already rotated that way).
Use "minsize" and "maxsize" to better control when log rotation is triggered.
> HCF-1203 Use copytruncate when rotating logs

- builder/role_image_test.go
- scripts/dockerfiles/run.sh
Trap SIGTERM and manually run monit stop all and wait for all processes to be stopped.
When monit is stopped, it doesn't automatically stop the processes it takes care of.
> HCF-1212 Stop all processes when a container is stopped

- scripts/dockerfiles/rsyslog_conf/etc/rsyslog.d/50-default.conf
The definition caused messages like "action 'action 18' suspended, next retry is ...".
Because xconsole does not exist in a container.
Passed build, unit tests.
Images build with the change have the proper changed rsyslog configration
(checked under vagrant)
> [HCF-1238] Disable logging to dev/xconsole

- model/job.go
Example: Making "uaa.clients.cf-usb.secret" dark does not mean that "uaa.clients" is dark.
This fix is required for https://github.com/hpcloud/hcf/pull/854
> [HCF-1912] Use type reflection to prevent inner nodes of the dark opinions to be seen as dark.

- app/fissile.go
- validation/errors.go
- validation/errors_test.go
- validation/rules.go
- validation/validation.go
- validation/validation_test.go
This PR introduces generic error types which can be put into chain in validation methods.
It helps collect all errors during validation and display them in the end.
For example when you execute `fissile build kube`:
```
run:    
scaling:
min: 1
max: 3    
memory: 256    
virtual-cpus: 4    
exposed-ports:
- name:                  #missing name
protocol: aaaa      #wrong protocol
external:               # missing port
internal: 4222   
public: false    
- name: nats-routes      
protocol: TCP      
external: 4223      
internal: 4223      
public: false
```
you get
```
$ fissile build kube
...
run.exposed-ports.name: Required value
run.exposed-ports[].external: Invalid value: "": invalid syntax
run.exposed-ports[].protocol: Unsupported value: "aaaa": supported values: TCP, UDP
```
> Add generic error types for validation purpose

- app/fissile.go
- app/fissile_test.go
- builder/packages_image.go
- builder/packages_image_test.go
- cmd/build-images.go
- cmd/build-packages.go
- cmd/root.go
- compilator/compilator.go
- compilator/compilator_test.go
- model/roles.go
- model/roles_test.go
This allows you to build only the packages required for a named selection of roles, or their images, instead of doing everything at once.
This should make it easier to CI things.
I'm introducing sub-vipers to work around issues where it gets confused if multiple subcommands use the same flag name.
> Add ability to build a subset of things

- builder/base_image_test.go
- model/job.go
- scripts/compilation/ubuntu-prerequisites.sh
- scripts/dockerfiles/Dockerfile-base
- scripts/dockerfiles/Dockerfile-role
- scripts/dockerfiles/monitrc.erb
We should make the name generic (right now, `fissile-compat-release`, and `fissile.*` for the BOSH properties).
I did not change /opt/hcf paths; that is expected to come later as it is more likely to have issues.
> Remove some mentions of HCF

- app/fissile.go
- kube/pod_test.go
- model/mustache.go
- model/roles.go
Ref https://trello.com/c/MwLhXpr3/14-env-vars-are-not-detected-properly-for-pods-it-looks-like-the-pods-get-more-than-they-need
> Fix env variables going into kube pods

- model/mustache.go
- model/mustache_test.go
- test-assets/role-manifests/tor-good.yml
When a spec calls for a property like `properties.foo`, also pick up environment variables listed in children like `properties.foo.bar`. This is required because when we eventually serialize `properties.foo` (via configgin) it will need `properties.foo.bar` in there somewhere.
> model: When looking for env vars, pick up descendent properties too

- docker/docker_test.go
- test-assets/extra-imports.go
Golang 1.8 no longer allows importing programs for side effects; instead we move it to a package we never build (unless on plan9, which we don't actually support anyway).
Fixes #221
> Fix compatibility with golang 1.8

- app/validation.go
- app/validation_test.go
- kube/pod_test.go
- model/mustache.go
- model/roles.go
- model/roles_test.go
- scripts/dockerfiles/run.sh
- test-assets/role-manifests/bad-cv-type-internal.yml
- test-assets/role-manifests/bad-cv-type.yml
- test-assets/role-manifests/templates-non.yml
- test-assets/role-manifests/tor-validation-ok.yml
- test-assets/role-manifests/volumes.yml
And register fissile's internal variables for use in templates.
Ticket: https://trello.com/c/e3sNBThS/63-fissile-it-s-broken
Rebased to include PR 220.
Rebased to include PR 225.
Latest changes include work for `type: user|environment`, `internal: true|false`.
Needs another review/look now.
Rebased to resolve conflicts, clean up of history. Now ready, IMVHO.
> Allow manifest private variables

- scripts/compilation/ubuntu-compile.sh
When building under docker, `${BOSH_INSTALL_TARGET}` is a symlink to `/fissile-out`.  When running chown on it, we need to follow that first symlink to make sure we actually change ownership of the files (and not the symlink itself).
> compile: follow /fissile-out symlink on final chown

- scripts/compilation/ubuntu-compile.sh
We need to use the fissile-built compilation image to actually build anything; however, that image already has a `/fissile-in` directory (because that's how the script to build the image was dropped in there). So we need to actually check for `/fissile-in/var/vcap` to know if we're building in docker.
> Make compile-without-docker detection stricter

- kube/pod.go
- kube/pod_test.go
- make/vet
- model/roles.go
Trello: https://trello.com/c/yVo0iMIM/119-3-fissile-should-have-a-timeout-setting-for-readiness-probes-and-other-probes-too-probably
> Make k8s probe timeouts configurable from role manifest

- .gitignore
- builder/packages_image.go
- builder/packages_image_test.go
- docker/docker.go
- docker/docker_test.go
- scripts/dockerfiles/Dockerfile-packages
Trello: https://trello.com/c/nKVdKHnE/147-fissile-version-change-no-longer-triggers-image-rebuild
Has https://github.com/SUSE/fissile/pull/240 stacked on top, same area of fissile, tested together
> Trigger rebuild for fissile version changes

- app/fissile.go
- kube/export_settings.go
- kube/pod.go
- kube/pod_test.go
- kube/secret.go
- model/roles.go
Trello https://trello.com/c/tk6NUmwT/85-3-k8s-secrets-should-be-secrets-not-env-vars
This change reworks the handling of the CVs marked secret in the manifest.
1. All manifest secrets are emitted as key/value-pairs inside of one or more K8s secrets (*)
2. When emitting the EV for CVs the secret CVs do not emit their value, but a reference to their secret+key from step 1. K8s then (should) arranges for the EV to have the value from the secret, without any intervention needed in manifest scripts and the like.
(Ad *) A K8s "secret" is a mini key/value database, i.e. a single K8s secret can hold multiple manifest secrets. Multiple K8s secrets come into play when the values from the manifest secrets together are larger than the storage limit on K8s secrets, currently 1MB (See `MaxSecretSize`). …
> Emit manifest secrets as K8s secrets, not as env vars.

- app/fissile.go
- app/fissile_test.go
- cmd/build-packages.go
- cmd/root.go
- cmd/show-release.go
- compilator/compilator.go
- compilator/compilator_linux_test.go
- compilator/compilator_test.go
Adds a verbose option to the `fissile show release` and `fissile build packages`
commands to show details about caching.
> Add verbose option with caching details

- app/fissile.go
- builder/packages_image.go
- builder/packages_image_test.go
- cmd/build-images.go
This makes it possible to build images without having docker running, which is required for CI.  If the stemcell ID is not given (the normal case), fissile will still ask docker for it.
> build images: allow manual --stemcell-id override

- app/fissile.go
- app/fissile_test.go
- cmd/build-packages.go
This adds a `--only-releases` option to `fissile build packages` such that it will not attempt to build packages not in the listed releases.
We wanted this for CI (so we can build all packages for a release, then throw them at the image builder)
> compilation: add option to only build packages from a subset of releases

- scripts/dockerfiles/run.sh
Fixes https://github.com/SUSE/fissile/issues/254.
`/var/spool/cron/tabs/` is SUSE specific.
> Test for existence of cron tabs dir before chown

- Godeps/Godeps.json
- kube/deployment.go
- kube/service.go
- kube/service_test.go
- kube/stateful_set.go
- kube/stateful_set_test.go
- test-assets/role-manifests/exposed-ports.yml
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/forward_requirements.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require.go.tmpl
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
- vendor/github.com/stretchr/testify/require/requirements.go
The public service will only include the ports marked as public; the private service continues to include all defined ports.
The public service will be called `$ROLENAME-public` while the private one is still called just `$ROLENAME`.
> Create separate public and private services in kube config and helm charts

- docs/kubernetes.md
- kube/service.go
- kube/service_test.go
- kube/stateful_set.go
- kube/stateful_set_test.go
Vlad liked it better than `-pod`.
> kube: change the statefulset headless service suffix to -set

- app/fissile.go
- kube/job_test.go
- kube/pod.go
- kube/pod_test.go
- model/roles.go
- test-assets/role-manifests/pods.yml
A `bosh-task` with the tag `stop-on-failure` is a basic Pod that won't
restart, even if it fails. This can be used to run tests where you need
it to fail, and not restart the pod, so the logs can be examined.
A job always tries to run to successful completion:
https://github.com/kubernetes/kubernetes/issues/20255
> Add `stop-on-failure` label

- builder/packages_image.go
- builder/packages_image_test.go
The package layer tag was accidentally including the template information. This is causing unnecessary rebuilds.
> Fix package layer signature calculation

- app/fissile.go
- builder/packages_image.go
- builder/packages_image_test.go
Naming it GetPackagesLayerImageName() should hopefully be less confusing
> builder: rename PackagesImageBuilder.GetRolePackageImageName()

- model/roles.go
This ensures that two builds using different checkouts can still get the same signature as long as they are at the same commit / using the same inputs.  This is necessary for CI as that puts each build in a checkout
with a random path.
> model/roles: Use relative paths in script signatures

- builder/role_image.go
https://trello.com/c/v6MxcwLW/229-fissile-build-images-output-dir-shouldnt-need-a-splatform-dir-for-uaa
Without outputDirectory use the original form, with org in the name.
> Drop docker org from the roleImageName when the outputDirectory is set.

- Makefile
- make/include/versioning
- make/release
- Add a release target packaging the fissile sources
- Retrieve version information from a .version file if it exists
> Add a release target and improve versioning

- make/release
readlink was executed in the make subfolder and thus the SRC variable was set wrong. Using GIT_ROOT instead as there has to be the source we want to package.
> Fix the problem with readlink being executed one directory too deep

- app/fissile.go
- cmd/build-packages.go
- compilator/compilator.go
- compilator/compilator_test.go
- docker/docker.go
or any other option here:
https://docs.docker.com/engine/userguide/networking/
it delegates to NetworkMode in this project:
https://github.com/fsouza/go-dockerclient/blob/4b8b44fdd6d7dc8ef1acec5f21582f339cfbdaaa/container.go#L697
Builds on OBS will work if `--network=host` otherwise we get errors (e.g. can't resolve "localhost" to "127.0.0.1").
@viovanov
> Add docker-network-mode argument to fissile build packages

- docs/configuration.md
- docs/validator-description.md
- model/mustache.go
- model/mustache_test.go
- scripts/dockerfiles/run.sh
These variables are generic enough that we should just put them in every container.  Update docs and tests to mention this.
> run.sh: Add KUBE_COMPONENT_INDEX / KUBE_SERVICE_DOMAIN_SUFFIX

- app/fissile.go
- helm/config.go
- helm/config_test.go
- kube/deployment.go
- kube/export_settings.go
- kube/pod.go
- kube/pod_test.go
- kube/stateful_set.go
- kube/utils.go
- kube/values.go
- model/roles.go
Note that memory and vcpu-count are generated but currently not used.
Both the sizing section and the role config files get a long role description as the header. It will start with a `description` from the role manifest (which we don't define yet) followed by a list of all jobs included in the role, including their descriptions. Unfortunately this is currently dominated by descriptions of our dummy bosh roles, so needs to be fixed as well.
The environment variables in `values.yaml` will now include the `example` value in a comment (if it is different from the default value).
Roles with a minimum replica count of 0 will be wrapped to exclude the definition if the actual count is 0.
Roles will include checks that the configured replica count is within the min/max range.
Any config variable …
> Generate scaling section in values.yaml

- kube/deployment.go
- kube/values.go
- model/roles.go
`ha` is the minimum number of instances required for HA. It defaults to `min` if not specified.
`must_be_odd` requires the instance count to be an odd number if this setting is `true`.
Also adds a global switch `sizing.HA` to `values.yaml` (defaults to `false`). If set to `true`, all the templates will use the `ha` value instead of the `min` value for the instance count (unless overridden by the user to a value different from the `min`).
Adds checks that all roles have at least `ha` instances when `sizing.HA` is true.
> Add additional role sizing options

- app/fissile.go
- builder/role_image.go
- builder/role_image_test.go
- cmd/build-helm.go
- cmd/build-images.go
- cmd/build-kube.go
- cmd/show-image.go
- kube/export_settings.go
- kube/pod.go
- model/roles.go
- model/roles_test.go
https://trello.com/c/HaqnE735/391-fissile-doesnt-have-enough-information-to-generate-good-docker-image-tags-when-scf-changes
Implementation should be complete. Unit tests pass.
Still needs testing within the context of a vagrant box building images.
Hm ... Coming to dislike the current name of the new option (`--version`).
The env var for that is `FISSILE_VERSION`, and completely does __not__ mean that.
To confusing.
A better env name would be `FISSILE_TAG_EXTRA`, and option `--tag-extra`.
Going for that now.
SCF PR = https://github.com/SUSE/scf/pull/1148 (🚧 No fissile master build yet)
This PR now ready for review.
> Add extra cli arguments to add more information for image tag calculation.

- helm/config.go
- kube/pod.go
- kube/pod_test.go
- testhelpers/serialization_helper.go
It wasn't doing anything useful for us; since the pre-start scripts run before monit comes up, that taking too long brings down the pod (and often breaks migrations).
The role manifest still could have explicit liveness probes.
> helm: drop default liveness probe

- app/fissile.go
- app/fissile_test.go
- kube/pod.go
- kube/rbac.go
- kube/values.go
- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/generate-auth.yml
- test-assets/role-manifests/rbac-missing-account.yml
- test-assets/role-manifests/rbac-missing-role.yml
For RBAC-based deployments, by default no permissions are granted to the service accounts.  We may end up needing some (to e.g. patch pod annotations).  This provides a mechanism to specify service accounts for
each role, and what (RBAC) roles are applied to each account.
Currently, this means we need to add a chunk to the role manifest to define the service account permissions for configgin to work:
```yaml
configuration:
auth:
roles:
configgin-role:
- apiGroups: [""] # In kube rbac, empty string means the default group
resources: [pods]
verbs: [get, list, patch]
- apiGroups: [""]
resources: [services]
verbs: [get]
accounts:
default:
roles: [configgin-role]
```
I'm not sure yet if we should just hard code that into fissile (which would mean updating fissile when we need to modify …
> Add support for RBAC accounts / roles

- kube/values.go
Configuration variables of the `CVTypeEnv` are not settable by the user but provided by the software, so listing them in `values.yaml` is confusing because they cannot be overridden.
> Hide environment variables from values.yaml

- app/fissile.go
- kube/secret.go
Secret generation is done as a job now. This allows them to be kept across upgrades instead of regenerating them.
> Remove secret generation from kube configs

- kube/job.go
- kube/pod.go
- kube/secret.go
We want jobs to run again during `helm upgrade`. This means we have to delete the job before creating it again, which helm doesn't support, except for helm "hooks".  Using a revision suffix creates a new Job that will still run while the old one can be removed because it is no longer included in the chart.
Also create a `RELEASE_REVISION` environment variable and append the revision to the `secret-update` name so the secrets generator can access the correct generation of this data.
> S4mXqwBB Append Release.Revision to Job names

- builder/role_image.go
- builder/role_image_test.go
- cmd/build-images.go
- scripts/dockerfiles/Dockerfile-role
- scripts/dockerfiles/run.sh
Ref: https://trello.com/c/ZNBu0nTv/4-5-remove-remaining-references-to-hcf-hcp
See commit e937051cf5 where this code was added (June 27, 2017).
:construction: Wait with merge, this has lots of related changes, see ticket.
:stop_sign: Do not merge until after the stemcells __in use__ are purged of the `opt/hcf` references.
> Drop the compatibility code for handling the deprecated /opt/hcf directory of older stemcells.

- kube/pod.go
- model/mustache.go
So far the assumption is that config variables of the "environment" type will be provided by the "system", e.g. via `run.sh`. But there may also be settings that are build-time choices (so users can't override), but still need to be available at runtime as env vars.
This will be used by SCF to configure the `SUSE_STACK` value, but will also create a `KUBE_AZ` variable, which currently is only promised but never instantiated.
> j8BtwZ51 Define "environment"-supplied variables if they have a default value

- app/fissile.go
- builder/packages_image.go
- cmd/build-packages.go
- compilator/compilator.go
- compilator/compilator_linux_test.go
- compilator/compilator_test.go
This makes sure that we use separate compilation results for changes in the stemcell used to compile it (e.g. different distro)
> compilation: Add stemcell name to compilation path

- app/fissile.go
- builder/packages_image.go
- docker/docker.go
- docker/docker_test.go
https://trello.com/c/cukB9mOo/308-fissiles-error-message-is-unhelpful-when-the-base-image-it-uses-for-building-images-is-unavailable
> Show a more sensible error for a missing base image

- cmd/build-helm.go
- kube/export_settings.go
- kube/values.go
- kube/values_test.go
Add a command line option to set the auth type in the generated
`values.yaml` file. The default remains `~`.
> Add auth-type option

- docs/configuration.md
- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/variables-badly-sorted.yml
- test-assets/role-manifests/variables-with-dup-prev-names.yml
Throw an error when
- a previous name is introduced again
- two previous names of different variables have the same name
> Validate previous_names section of config vars

- app/fissile.go
- kube/deployment.go
- kube/service.go
- kube/stateful_set.go
This PR changes how clustered roles work: there is no service generated any more, and the corresponding configgin changes handle this by getting the instance info from the StatefulSet.
https://github.com/SUSE/configgin/pull/64/files
The old style of services will be called `indexed` in our role manifest. Currently, only doppler will get the `clustered` tag, but I expect others will be updated as well.
The reason for removing services is it ensures we aren't accidentally using the load balanced hostname (e.g. `doppler.svc.cf.cluster.local`), instead we use a list of specific hostnames.
> Handle indexed tag

- builder/role_image.go
- builder/role_image_test.go
- kube/pod.go
- kube/pod_test.go
- scripts/dockerfiles/Dockerfile-role
- scripts/dockerfiles/pre-stop.sh
- scripts/dockerfiles/run.sh
This adds a Kubernetes pre-stop script which implements the [BOSH job stop lifecycle](https://bosh.io/docs/job-lifecycle.html#stop), including [drain scripts](https://bosh.io/docs/drain.html).  Note that this doesn't extend the time out for shut down, so it may terminate prematurely (but at least it does _something_).
There were some cleanups to `run.sh` too because I thought that was where part of the logic was going to live (it ended up being a dead end).
> Run BOSH drain scripts

- Makefile
- builder/role_image_test.go
- make/bindata
- make/clean
* The scripts/dockerfiles/dockerfiles.go file must exist (make bindata).
* The docker/mock_dockerclient_generated.go file must exist (make test).
* The asyncError variable in builder/role_images.go must be referenced.
This commit also removed an outdated comment from make/bindata.
> Adjust to changes in go-vet 1.10

- kube/service.go
- kube/values.go
This exposes the list nature of the external IP to the configuration, so that in setups where multiple IPs are desired (e.g. for a HA-ish setup) that can be used.
The old-style single-IP configuration is still supported
> Allow multiple IPs for external IP

- helm/config.go
- helm/config_test.go
The helm chart needs external_ips to be an empty list, so that the helm chart can append to it successfully.
Fixes an issue with #326
> helm: Output empty lists

- scripts/dockerfiles/run.sh
If monit has already exited, it can't possibly respond to queries about if the processes are still running.  In that case, just stop asking.
> run.sh: abort waiting for monit if monit is missing

- cmd/build-helm.go
- cmd/build-kube.go
- kube/deployment.go
- kube/export_settings.go
- kube/pod.go
- kube/pod_test.go
- kube/values.go
Ref: https://trello.com/c/UEvqSutH/576-sane-memory-limits-for-all-pods
See also SCF branch https://github.com/SUSE/scf/tree/aku/UEvqSutH-mem-limits
where the role-manifest is modified based on memory measurements for the SCF roles.
> Extend fissile to generate proper memory requests and limits.

- helm/config.go
- helm/config_test.go
- kube/service.go
This causes unnecessary upgrade failures (due to new, empty, volume lists).  See bsc#1084412
> Don't allow empty lists

- kube/utils.go
Ignore the "+" in "1.8+" on GKE.
> Only use numeric part of minor kube version

- cmd/build-helm.go
- cmd/build-kube.go
- kube/deployment.go
- kube/export_settings.go
- kube/pod.go
- kube/pod_test.go
- kube/values.go
- model/roles.go
- test-assets/role-manifests/bad-cv-type-internal.yml
- test-assets/role-manifests/bad-cv-type.yml
- test-assets/role-manifests/bosh-run-bad-memory.yml
- test-assets/role-manifests/bosh-run-missing.yml
- test-assets/role-manifests/docker-run-env.yml
- test-assets/role-manifests/multiple-good.yml
- test-assets/role-manifests/non-bosh-roles.yml
- test-assets/role-manifests/pods.yml
- test-assets/role-manifests/templates-non.yml
- test-assets/role-manifests/tor-good.yml
- test-assets/role-manifests/tor-validation-issues.yml
- test-assets/role-manifests/tor-validation-ok.yml
- test-assets/role-manifests/variables-badly-sorted.yml
- test-assets/role-manifests/variables-without-decl.yml
- validation/validation.go
Ref: https://trello.com/c/6925zx7v/584-2-cpu-being-able-to-enable-cpu-limits-whilst-leaving-them-off-by-default
Both cpu and memory request and limits got redone.
For the spec worked from see the ref above, top comments from Mar 9.
* The limit-factors are gone. Role manifest specifies both requests and limits, no implicit coupling.
* By default all requests and limits are globally off in the `values.yaml`.
* The inactive defaults are inherited from the manifest.
* It is possible to set a request or limit for a specific role to `~` , i.e. null and the role will disable this when starting the role. The template checks both global flag and per-role information before activating a request or limit (`if and ...`).
Currently tested against SCF, with the memory limits.
Inactive, globally active, …
> Implement CPU limits in fissile. Analogous to memory limits.

- kube/utils.go
Because the latter requires helm 2.7.0+ and our Jenkins images
only have 2.6.2.
> Use trimSuffix instead of regexFind function

- app/fissile.go
Hi,
`LICENSE` is not required for loading a final release, so remove it from final release check. Thanks!
> Remove LICENSE Check for a final release

- kube/pod.go
When deploying kube (non-helm) things such as tests, we get validation errors:
```
error validating data: [
unknown object type "nil" in Pod.spec.containers[0].resources.limits.cpu,
unknown object type "nil" in Pod.spec.containers[0].resources.limits.memory
]
```
> kube: Don't add nil memory/cpu limits

- app/fissile.go
- model/release.go
We have a mix of development and final releases in our builds. It would help to quickly see which ones were originally final releases where we supplied the tarball and which ones were compiled from scratch for the build.
I added a function to return the release type, which is either `Dev` or `Final`.
The UI print functions were modified to call the release type
function to print it in the `fissile show release` output, e.g.
```
Final release nginx (1.12.2+dev.1)
nginx (e7dc968f9daf5b31ff4ad6edf048306f45a70bbb):
There are 1 jobs present.
Final release nginx (1.12.2+dev.1)
nginx (d6ddf5c4782669341b260a27c53208d32a17b3a5)
There are 1 packages present.
```
What do you think about this idea? Thanks in advance for your feedback.
> Return the release type Dev or Final in fissile show release

- Makefile
- kube/deployment.go
- kube/deployment_test.go
- make/show-versions
Updated unit tests (also removal).
General add-in of version information target.
https://trello.com/c/3MB6uqby/607-1-deprecate-kube-15-affinity-support-in-fissile
> Drop support for kube 1.5 affinity annotations.

- app/fissile.go
- app/fissile_test.go
Sort the hashes by key, and deal with indents.  This makes it easier to compare across releases (reducing false positives caused by runtime differences in hash ordering).
Also, adjust the diff output so it's easier to tell what is a job-specific property.
> diff: better formatting for hashes

- app/fissile.go
- kube/pod.go
- kube/pod_test.go
- kube/stateful_set.go
- kube/stateful_set_test.go
- kube/values.go
- model/roles.go
- test-assets/role-manifests/volumes.yml
- testhelpers/helm_helper.go
- testhelpers/serialization_helper.go
This adds support for hostpath volumes, for SUSE/scf#1345 to mount the external `/sys/fs/cgroup` in `diego-cell`.  It also accepts (but does not implement) emptyDir volumes, sort of on the way to #340 (if we decide to implement this way, rather than `empty-dir: true` as suggested).
This is more for discussion than merging; for one thing, I'm not sure hostpath would always be available.
> Support hostpath volumes

- README.md
- app/fissile.go
- docs/configuration.md
- docs/kubernetes.md
- make/clean
This forces the explicit use of tags at roles to trigger their creation.
Further tweaked make, announce cleaning like all the other ops.
https://trello.com/c/0zylWw07/606-2-fissile-statefulsets-should-be-explicitly-defined
Dependent: https://github.com/SUSE/scf/pull/1456
Dependent: https://github.com/SUSE/uaa-fissile-release/pull/94
> Drop auto-creation of stateful sets for roles with volume decls.

- kube/stateful_set.go
- kube/stateful_set_test.go
- model/roles.go
- test-assets/role-manifests/kube/volumes-with-annotation.yml
Hi, 
This PR contains a new field in the `RoleRunVolume` structure,  to allow persistent and shared
volumes annotations to be customizable.  This is for use cases where the default annotation is not enough for the IaaS, and additional ones are required. Also, the default one, should be allow to be overwritten based on the user needs.
> Add configurable annotations to volumes

- kube/deployment.go
- kube/deployment_test.go
- kube/pod_test.go
- kube/secret_test.go
- kube/service_test.go
- kube/stateful_set.go
- kube/stateful_set_test.go
- testhelpers/helm_helper.go
Cannot check FOO.BAR when FOO is nil.
Cannot `and FOO FOO.BAR` because `and` is not short-circuited.
Matched tests (changed column indices in the error messages)
Ref https://trello.com/c/7xGqgWkI/671-3-make-sizing-section-of-valuesyaml-uniform
> Fix the generated guard conditions.

- kube/values.go
- kube/values_test.go
This adds a comment in the sizing section to describe how the role names are generated (since those are not literally the names of the roles).
> kube: values: Describe role names in the sizing section

- app/fissile.go
- builder/role_image.go
- builder/role_image_test.go
- helm/config.go
- kube/deployment.go
- kube/deployment_test.go
- kube/pod.go
- kube/pod_test.go
- kube/secret_test.go
- kube/service.go
- kube/service_test.go
- kube/stateful_set.go
- kube/stateful_set_test.go
- kube/values.go
- model/roles.go
- model/roles_test.go
- scripts/dockerfiles/Dockerfile-role
- scripts/dockerfiles/readiness-probe.sh
- test-assets/role-manifests/app/two-roles.yml
- test-assets/role-manifests/kube/service-headed.yml
- test-assets/role-manifests/kube/service-headless.yml
- test-assets/role-manifests/model/bosh-run-headless-public-port.yml
- test-assets/role-manifests/model/colocated-containers-with-clustered-tag.yml
- test-assets/role-manifests/model/colocated-containers-with-port-collision.yml
- testhelpers/helm_helper.go
- testhelpers/serialization_helper.go
This implements the [Pod Management using Role Manifest Tags](https://github.com/SUSE/fissile/wiki/Pod-Management-using-Role-Manifest-Tags) document.
Notable changes:
- We only use statefulset now
- The tags are all changed
- Dev-only roles are no longer a thing (it really hasn't for a while, since we deploy via kube now)
- BOSH roles will actually look at `monit` for the readiness
- For active/passive roles, a command line is used to determine when it's ready (at which point a label is applied to the pod)
- I use lists of constants (since we don't have actual enums in golang) more, and raw strings less.
- For some reason, the old kube stuff was (incorrectly) outputting `externalIPs` as a single string instead of a list
This should probably wait for #352 to land first — that started …
> Rework pod management

- docs/configuration.md
- docs/validator-description.md
- kube/deployment_test.go
- kube/job_test.go
- kube/pod_test.go
- model/mustache.go
- model/mustache_test.go
- scripts/dockerfiles/run.sh
It can always be replaced by $KUBERNETES_NAMESPACE.svc.$KUBERNETES_CLUSTER_DOMAIN
Please create new `5.3.0` tag on the merge commit
> Drop support for KUBE_SERVICE_DOMAIN_SUFFIX

- kube/service.go
- kube/service_test.go
- kube/stateful_set_test.go
Automatically provisioning load balancers in Azure (and likely other container services) was broken because of two issues:
* load balancers were being created for non-public services
* external IPs were being defined for public services even though a load balancer was requested
These changes only use `externalIP`s if `loadbalanced == False`, and only request load balancers for `-public` services. A public service is created if the role manifest's `exposed-port` definition has `public: true`
In the second commit I simplified the `ClusterIP` setting since it's the default. It wraps the loadbalancer type in a block rather than the if/else statement. I feel that's simpler, although it's less obvious for the `ClusterIP` setting because that's not explicit any more. If there's any objections I …
> Only use external ips for non loadbalanced mode

- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/model/colocated-containers-with-no-port-collision.yml
Replace lookup logic used in port collision check to use the tuple of
protocol and port (`TCP/53`). That way a port collision is only counted
in case both roles use the same protocol. The same port used by both
protocols is no longer falsely reported as a configuration issue.
This should fix #364.
> Fix port collition check problem

- scripts/dockerfiles/readiness-probe.sh
On my deployments I see monit using a lot of CPU because of this.
Replacing with a curl call that grabs status from the monit daemon using using the HTTP api.
> Don't use "monit summary" in container readiness probe

- kube/service.go
- kube/service_test.go
- kube/stateful_set_test.go
When multiple port definitions exist on a pod with the same containerPort (but different external ports), we need to end up using the first one for the service definition as kubernetes has trouble correctly modifying the port definitions on upgrades.  The easiest way to make that work is to just use the numeric port number for the service targetPort, which will end up referring to whichever container port definition that works.
> kube: services: use the port number for targetPort definitions

- app/fissile.go
- kube/pod.go
- kube/pod_test.go
- kube/secret.go
- kube/secret_test.go
- kube/values.go
- model/configuration.go
- model/mustache.go
- model/roles.go
- model/roles_test.go
- model/variables.go
- model/variables_test.go
- test-assets/deployment-manifests/bosh-deployment.yml
- test-assets/role-manifests/app/hashmat.yml
- test-assets/role-manifests/app/tor-validation-issues.yml
- test-assets/role-manifests/app/tor-validation-ok.yml
- test-assets/role-manifests/builder/tor-good.yml
- test-assets/role-manifests/kube/colocated-containers-with-stateful-set-and-empty-dir.yml
- test-assets/role-manifests/kube/volumes.yml
- test-assets/role-manifests/model/bad-cv-type-internal.yml
- test-assets/role-manifests/model/bad-cv-type.yml
- test-assets/role-manifests/model/bosh-run-missing.yml
- test-assets/role-manifests/model/templates-non.yml
- test-assets/role-manifests/model/variable-expansion.yml
- test-assets/role-manifests/model/variables-badly-sorted.yml
- test-assets/role-manifests/model/variables-with-dup-prev-names.yml
- test-assets/role-manifests/model/variables-without-decl.yml
- test-assets/role-manifests/model/variables-without-usage.yml
Implements BOSH variables section for https://github.com/SUSE/fissile/issues/370
This relies on https://github.com/SUSE/scf-secret-generator/pull/30
* removed Generator
* SSL private keys and SSH fingerprints no longer have a separate entry,
* all variable options are now below options
* containerization specific variables are also below options
* variables have a type instead of a Generator
* in contrast to BOSH empty type is supported for role manifest
* subject_names is now alternative_names
https://www.pivotaltracker.com/story/show/160013630
> Switch to BOSH manifest style variables

- kube/pod.go
- kube/pod_test.go
- kube/service.go
- kube/service_test.go
- kube/stateful_set_test.go
- kube/values.go
- model/instance_groups.go
- model/job.go
- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/kube/bosh-run-count-configurable.yml
- test-assets/role-manifests/kube/exposed-ports.yml
- test-assets/role-manifests/kube/service-headed.yml
- test-assets/role-manifests/kube/service-headless.yml
- test-assets/role-manifests/model/bosh-run-bad-parse.yml
- test-assets/role-manifests/model/bosh-run-bad-port-count.yml
- test-assets/role-manifests/model/bosh-run-bad-port-names.yml
- test-assets/role-manifests/model/bosh-run-bad-ports.yml
- test-assets/role-manifests/model/bosh-run-bad-proto.yml
- test-assets/role-manifests/model/bosh-run-headless-public-port.yml
- test-assets/role-manifests/model/bosh-run-missing-portrange.yml
- test-assets/role-manifests/model/bosh-run-ok.yml
- test-assets/role-manifests/model/bosh-run-reverse-portrange.yml
- test-assets/role-manifests/model/colocated-containers-with-clustered-tag.yml
- test-assets/role-manifests/model/colocated-containers-with-no-port-collision.yml
- test-assets/role-manifests/model/colocated-containers-with-port-collision.yml
Resolves https://github.com/SUSE/fissile/issues/367
> Use one kube service per bosh job

- kube/pod.go
- kube/pod_test.go
- model/instance_groups.go
- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/model/docker-run-env.yml
We don't support docker roles anymore. However they create problems when moving the run property from the `InstanceGroup` to the `JobReferences` properties. `Run` is required on at least one job and docker roles don't have jobs (?). So lets remove them.
Unsure if these are all the places.
> Remove support for instance groups of the `docker` type

- app/fissile.go
- app/fissile_test.go
- kube/pod.go
- kube/rbac.go
- kube/rbac_test.go
- kube/utils.go
- model/configuration.go
- model/job.go
- model/pod_security_policy.go
- model/pod_security_policy_test.go
- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/model/rbac-clone-sa-psp-mismatch.yml
- test-assets/role-manifests/model/rbac-illegal-psp.yml
- test-assets/role-manifests/model/rbac-merge-psp.yml
- test-assets/role-manifests/model/rbac-ok-psp.yml
Ref: https://trello.com/c/9EmTR4JL/775-3-add-psp-support-to-fissile-and-role-manifests
Ref: https://github.com/SUSE/fissile/wiki/Managing-Pod-Security-Policies
:warning: This is based on PR #382 and cannot be merged before it.
> Add PSP support

- model/roles.go
- model/roles_test.go
- test-assets/role-manifests/model/bad-type.yml
* containerization also allows "" as a BOSH type
* adapt error message for fissile type, as it moved below the `options` key
https://www.pivotaltracker.com/story/show/160497595
> Validate bosh type

- app/fissile.go
- app/fissile_test.go
- model/configuration.go
- model/roles.go
Ref: https://trello.com/c/PMrNrMOh/799-3-fissile-change-to-generate-roles-role-bindings-in-the-kube-files-if-only-one-instance-group-is-using-that-role
This change results in fissile generating a less cluttered helm chart. Accounts and roles bound just to things like a test task (irrelevant to helm), for example, will not appear in the helm chart any longer.
The effect is implemented by fissile maintaining usage/reference counters for accounts and roles when iterating over instance groups during load.  When writing files the accounts and roles with a single user are ignored by the code creating separate files, and the code writing instance groups is extended to take over that task instead.
:warning: This PR currently sits on top of …
> Move writing of service accounts and roles bound to a single instance group from separate files to the file for the instance group.

- Makefile
- make/vet
`make/vet` still requires `make/bindata` to be run first to generate `scripts/compilation/compilation.go`
> Call `go generate` to generate docker mocks for make/vet

- scripts/dockerfiles/readiness-probe.sh
The monit status HTTP curl call should fail
- when monit daemon is not up
- Add pipefail to produce a failure return code if any cmd of
the pipe fails when checking the monit status
- Double quote vars to prevent globbing/word splitting(SC2086 shellcheck)
> For readiness probe, ensure that monit daemon is up

- vendor/github.com/mholt/archiver/tar.go
> Fix link target name for symbolic links in tar archive

- README.md
I'm following the steps to build Fissile [here](https://github.com/cloudfoundry-incubator/fissile#build-procedure)
- Updated Go version, as Go 1.7 and 1.8 not works for me and 1.9 works well.
- Added minor details to build Fissile
```
zhanggongs-mbp:fissile (upstream_develop*) $ gvm use go1.7                                                    
zhanggongs-mbp:fissile (upstream_develop*) $ make all     
/Users/zhanggong/zhgworkspace/fissile/src/code.cloudfoundry.org/fissile/make/clean
==> Cleaning 
/Users/zhanggong/zhgworkspace/fissile/src/code.cloudfoundry.org/fissile/make/format
==> Formatting 
/Users/zhanggong/zhgworkspace/fissile/src/code.cloudfoundry.org/fissile/compilator/storage.go:36:28: expected type, found '='
/Users/zhanggong/zhgworkspace/fissile/src/code.cloudfoundry.org/fissile/ …
```
> [README]Update Fissile build procedure

- kube/rbac.go
- kube/rbac_test.go
Keep the definitions in different charts apart from each other.
Updated tests.
Ref: https://trello.com/c/KzfK2xOh/822-13-rc-deploy-issue-with-psp-cluster-roles
:warning: While it passes the unit tests this is still to be tested with scf.
> Prefix the global entities clusterrole(binding) with namespace information.

- Makefile
- make/test
- make/vet
This makes it possible to run all the build steps of `make all` in arbitrary order, e.g. `make clean vet`, `make clean test` etc all work now.
Running `make all` will now result in running make/bindata multiple times. But given that it takes just a couple of milliseconds this doesn't really matter.
The docker images are not required for any of the other build steps, so they are no longer pulled as part of the `make all` command.
> Call make/bindata whenever required

- kube/deployment_test.go
- kube/registry_credentials_test.go
- kube/secret_test.go
- kube/service_test.go
- kube/stateful_set_test.go
- kube/utils.go
- kube/utils_test.go
- test-assets/role-manifests/kube/pod-with-valid-pod-anti-affinity.yml
We'll keep the skiff-role-name label around for a while in case it is being used by end users.
> Replace skiff-role-name with app.kubernetes.io/component

- make/test
make/docker-deps was erroneously removed in #421 because it isn't used for building the tool.
It is required for running the tests though.
> make/docker-deps is a prereq for make/test

- kube/utils.go
Chart versions can be numeric, but kubernetes chokes on numeric label
values, resulting in errors like
```
Error: release my-nats failed: Secret in version "v1" cannot be handled
as a Secret: v1.Secret: Type: ObjectMeta: v1.ObjectMeta: Namespace:
Name: Labels: ReadString: expects " or n, but found 1, error found in
#10 byte of ...|version":1,"helm.sh/|..., bigger context
...|s.io/name":"my-nats","app.kubernetes.io/version":1,"helm.sh/chart":"my-nats-1","skiff-role-name":"re|...
```
To fix this the version label value is always quoted.
> Fix helm charts with numeric versions

- kube/stateful_set.go
This is required to work around
https://github.com/helm/charts/issues/7726, without it we see errors like
```
Error: UPGRADE FAILED: StatefulSet.apps "nats" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/managed-by":"Tiller", "app.kubernetes.io/name":"my-nats", "app.kubernetes.io/version":"", "helm.sh/chart":"my-nats-10", "skiff-role-name":"nats", "app.kubernetes.io/component":"nats", "app.kubernetes.io/instance":"my-nats"}: `selector` does not match template `labels`
```
during helm upgrades.
> Add a matchLabels selector to stateful sets as well

- kube/deployment_test.go
- kube/job_test.go
- kube/pod.go
- kube/pod_test.go
- model/instance_groups.go
- model/pod_security_policy.go
- model/roles.go
When using pod security policies, it is likely that (for the unprivileged policy at least) we are not allowed to escalate privileges. This means that pods will fail to start if they ask for escalation.
For some crazy reason, kube seems to default `allowPrivilegeEscalation` to true when not supplied (when fetching the pod metadata, not when running); this means that attempting to patch the pod (to update the configgin annotations) will fail because even a no-op patch is considered an escalation.  Fix this by explicitly marking the pods as not requiring the escalation.
> helm+kube: default to not allowing privilege escalation

- README.md
This belongs to issue #374 
Maybe we should add SCF, too?
And https://github.com/SUSE/scf-helper-release and https://github.com/SUSE/uaa-fissile-release?
> Add example releases to README

- model/instance_groups_test.go
- model/job_reference_test.go
- model/roles_test.go
After splitting the models across more files, tests were not moved to corresponding files
> move tests to files

- scripts/dockerfiles/run.sh
The symlinks from /var/vcap/packages to ../packages-src do not resolve inside a bpm container, so move the packages over instead.
bosh also creates a number of convenience symlinks under /var/vcap/data that this commit simply emulates.
> Adjust /var/vcap layout for bpm compatibility

- app/fissile.go
- kube/bosh_deployment_manifest_secret.go
- kube/bosh_deployment_manifest_secret_test.go
- kube/kube_test.go
- kube/pod.go
- kube/pod_test.go
- kube/stateful_set_test.go
- scripts/dockerfiles/run.sh
The `values.yml` can now embed a BOSH deployment manifest under the `bosh` key, e.g.
```yaml
---
bosh:
instance_groups:
- name: nats
jobs:
- name: nats
properties:
nats:
port: 4333
env:
DOMAIN: bosh.io
```
The manifest part will be extracted into a kubernetes secret and mounted in the pods (at `/opt/fissile/config/deployment-manifest.yml`) so that configgin can pick it up.
> Add support for embedded deployment manifests in the values.yml

- util/download_file_test.go
Hi,
While I was digging the codebase, noticed that ```DownloadFile``` missed a test file. The test is actually creating a small http server so it can be performed in network sandboxed environments.
> Add test for util.DownloadFile

- model/job.go
- model/job_reference_test.go
- model/roles.go
- model/roles_test.go
This is so configgin can use it to construct the correct host name to contact (when resolving BOSH links).
> model: expose service_name in config_spec.json (for jobs)

- kube/pod.go
- kube/pod_test.go
Otherwise kube will reject the pod with:
create Pod … in StatefulSet … failed error: Pod … is invalid:
… cannot set `allowPrivilegeEscalation` to false and
`privileged` to true
>  kube/pod.go: force allowPrivilegeEscalation if privileged
